### ISSUE TITLE
Вопрос по линукс и dolphin-anty

### ISSUE THREAD

**Issue by listmen001** [IsNaRm/dolphin-free-botsforge#2]
Винда не такая ровная и линукс всегда лучше!
уже убедился и желаю этого добра каждому!
На винде пробовал и все получилось!
Но!
на линуксе все по другому!
Как сделать все на линуксе?
![image](https://github.com/IsNaRm/dolphin-free-botsforge/assets/72976151/42d80623-0476-4ee9-9474-5013d6abe9ed)
Вот так выглядит папка после запуска исполняемого файла.

**Comment by IsNaRm** [comment]
> Как сделать все на линуксе?
Добавил мануал в описание
