### ISSUE TITLE
Вопрос по показу профилей с запуском скрипта

### ISSUE THREAD

**Issue by Wisp-k** [IsNaRm/dolphin-free-botsforge#3]
![image](https://github.com/IsNaRm/dolphin-free-botsforge/assets/142631410/a4b568b4-b50e-4a31-a7f1-69cba689c036)
Всё было нормально, создавал профиля, но тут они пропали. 
Они так же создаются, но не появляются не ранее созданные, не новые.
Посмотрел основные вопросы, страничку перелестнуть не получается

**Comment by Wisp-k** [comment]
![image](https://github.com/IsNaRm/dolphin-free-botsforge/assets/142631410/3bd7e377-d67f-440f-9a96-31e29117146d)

**Comment by IsNaRm** [comment]
Один из профилей битый
